name: Build and Deploy to gh-pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish .NET Core Project
      run: dotnet publish Portfolio.csproj -c Release -o release --nologo

    # Change base-tag in index.html from '/' to 'NewPortfolio' to match GitHub Pages repository subdirectory
    - name: Change base-tag in index.html from / to NewPortfolio
      run: sed -i 's/<base href="\/" \/>/<base href="\/NewPortfolio\/" \/>/g' release/wwwroot/index.html

    # Copy index.html to 404.html to serve the same file when a file is not found
    - name: copy index.html to 404.html to serve the same file when a file is not found
      run: cp release/wwwroot/index.html release/wwwroot/404.html

    # Add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll

    - name: Deploy to gh-pages branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: release/wwwroot
        publish_branch: gh-pages
